### ISSUE TITLE
Installing plugin via Eclipse update site fails

### ISSUE THREAD

**Issue by venushka** [eclipse-jetty/eclipse-jetty.github.io#5]
I've been trying to install this plugin recently using the update site and has been failing for a while. This used to work with the exact same configuration before. This is what I am seeing.

<img width="862" alt="step-1" src="https://user-images.githubusercontent.com/4840772/210585033-16052dde-bcaf-4d2d-9f9a-00a7027fefb6.png">

<img width="861" alt="step-2" src="https://user-images.githubusercontent.com/4840772/210585059-d062783c-5793-42fe-89c8-46da9b29ba55.png">

<img width="1123" alt="error" src="https://user-images.githubusercontent.com/4840772/210585080-bc3d9899-a6bd-46a7-9303-ecb819e6fa6f.png">

If there's any other information I can provide to help investigate this issue, I am happy to do so.

Eclipse version: 2022-12 (also I've noticed this on 2021-12)

**Comment by derkoe** [comment]
Should be resolved - this line was missing:
https://github.com/eclipse-jetty/eclipse-jetty.github.io/blob/a77bc5216cb43eda86b1ff41fb415e066dd094d6/update/compositeArtifacts.xml#L12
